server:
  port: 5000
  tomcat:
    use-relative-redirects: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth
    username: oauth
    password: oauthuserpassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
